### ISSUE TITLE
Mmdetection version

### ISSUE THREAD

**Issue by Huanghong98** [cxliu0/KL-Loss-pytorch#3]
Hello, I would like to know which version of mmdetection you are using? thank you!

**Comment by cxliu0** [comment]
The version we used is 2.4.0 (see [here](https://github.com/cxliu0/KL-Loss-pytorch/blob/main/mmdet/version.py#L3)).

**Comment by Huanghong98** [comment]
> The version we used is 2.4.0 (see [here](https://github.com/cxliu0/KL-Loss-pytorch/blob/main/mmdet/version.py#L3)).

Thank you very much!
